// Package dnsconf wires macOS name resolution to the dnsmasq container.
//
// macOS reads /etc/resolver/<tld> natively: any file there routes that TLD to
// the listed nameserver. That gives a true wildcard -- a project registered
// tomorrow resolves with no further DNS work -- which is why this is preferred
// over appending lines to /etc/hosts.
package dnsconf

import (
	"fmt"
	"net"
	"os"
	"os/exec"
	"runtime"
	"strings"
)

func Path(domain string) string { return "/etc/resolver/" + domain }

func content(port int) string {
	return fmt.Sprintf("# Generated by dragonrun.\nnameserver 127.0.0.1\nport %d\n", port)
}

func Supported() bool { return runtime.GOOS == "darwin" }

// Installed reports whether the resolver file exists AND matches what we would
// write -- a stale file pointing at the wrong port fails in a way that looks
// like DNS simply not working.
func Installed(domain string, port int) bool {
	b, err := os.ReadFile(Path(domain))
	return err == nil && strings.TrimSpace(string(b)) == strings.TrimSpace(content(port))
}

// Install writes the resolver file via sudo tee. /etc/resolver is root-owned
// and usually does not exist on a fresh machine.
func Install(domain string, port int) error {
	if !Supported() {
		return fmt.Errorf("/etc/resolver is macOS-only; on %s point your resolver at 127.0.0.1:%d "+
			"or add per-project entries to /etc/hosts", runtime.GOOS, port)
	}
	if err := run("sudo", "mkdir", "-p", "/etc/resolver"); err != nil {
		return err
	}
	tee := exec.Command("sudo", "tee", Path(domain))
	tee.Stdin = strings.NewReader(content(port))
	tee.Stdout, tee.Stderr = os.Stderr, os.Stderr // keep stdout clean for scripts
	if err := tee.Run(); err != nil {
		return err
	}
	// Without this the resolver cache keeps serving NXDOMAIN for a while.
	_ = run("sudo", "dscacheutil", "-flushcache")
	_ = run("sudo", "killall", "-HUP", "mDNSResponder")
	return nil
}

func Uninstall(domain string) error {
	if err := run("sudo", "rm", "-f", Path(domain)); err != nil {
		return err
	}
	_ = run("sudo", "dscacheutil", "-flushcache")
	_ = run("sudo", "killall", "-HUP", "mDNSResponder")
	return nil
}

// Addrs asks the OS -- not the config file -- what a name resolves to, which
// is the only question that matters end to end: resolver reachable, wildcard
// in place, cache not serving a stale NXDOMAIN.
//
// dscacheutil rather than net.LookupHost because it goes through the same
// resolver stack (/etc/resolver included) that every other program on the Mac
// uses, and Go's resolver does not always.
func Addrs(host string) []string {
	out, err := exec.Command("dscacheutil", "-q", "host", "-a", "name", host).Output()
	if err != nil {
		return nil
	}
	var ips []string
	for _, line := range strings.Split(string(out), "\n") {
		for _, k := range []string{"ip_address: ", "ipv6_address: "} {
			if v, ok := strings.CutPrefix(strings.TrimSpace(line), k); ok {
				ips = append(ips, strings.TrimSpace(v))
			}
		}
	}
	return ips
}

// Local reports whether an address belongs to this machine.
//
// Loopback is the common answer, but not the only correct one: a network-wide
// rewrite (AdGuard Home, Pi-hole, a router) usually points the domain at the
// host's LAN address so phones and other machines resolve it too. That is a
// working setup, and a check that insists on 127.0.0.1 calls it broken.
func Local(ip string) bool {
	addr := net.ParseIP(ip)
	if addr == nil {
		return false
	}
	if addr.IsLoopback() {
		return true
	}
	ifaces, err := net.InterfaceAddrs()
	if err != nil {
		return false
	}
	for _, a := range ifaces {
		if n, ok := a.(*net.IPNet); ok && n.IP.Equal(addr) {
			return true
		}
	}
	return false
}

// Loopback reports whether an address is this machine's loopback.
func Loopback(ip string) bool {
	addr := net.ParseIP(ip)
	return addr != nil && addr.IsLoopback()
}

// Resolves reports whether the name resolves to an address this machine
// answers on -- the wildcard working, by whichever route.
func Resolves(host string) bool {
	ips := Addrs(host)
	for _, ip := range ips {
		if !Local(ip) {
			return false
		}
	}
	return len(ips) > 0
}

func run(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Stdout, cmd.Stderr, cmd.Stdin = os.Stderr, os.Stderr, os.Stdin
	return cmd.Run()
}
