// Package dnsconf wires macOS name resolution to the dnsmasq container.
//
// macOS reads /etc/resolver/<tld> natively: any file there routes that TLD to
// the listed nameserver. That gives a true wildcard -- a project registered
// tomorrow resolves with no further DNS work -- which is why this is preferred
// over appending lines to /etc/hosts.
package dnsconf

import (
	"fmt"
	"os"
	"os/exec"
	"runtime"
	"strings"
)

func Path(domain string) string { return "/etc/resolver/" + domain }

func content(port int) string {
	return fmt.Sprintf("# Generated by dragonrun.\nnameserver 127.0.0.1\nport %d\n", port)
}

func Supported() bool { return runtime.GOOS == "darwin" }

// Installed reports whether the resolver file exists AND matches what we would
// write -- a stale file pointing at the wrong port fails in a way that looks
// like DNS simply not working.
func Installed(domain string, port int) bool {
	b, err := os.ReadFile(Path(domain))
	return err == nil && strings.TrimSpace(string(b)) == strings.TrimSpace(content(port))
}

// Install writes the resolver file via sudo tee. /etc/resolver is root-owned
// and usually does not exist on a fresh machine.
func Install(domain string, port int) error {
	if !Supported() {
		return fmt.Errorf("/etc/resolver is macOS-only; on %s point your resolver at 127.0.0.1:%d "+
			"or add per-project entries to /etc/hosts", runtime.GOOS, port)
	}
	if err := run("sudo", "mkdir", "-p", "/etc/resolver"); err != nil {
		return err
	}
	tee := exec.Command("sudo", "tee", Path(domain))
	tee.Stdin = strings.NewReader(content(port))
	tee.Stdout, tee.Stderr = os.Stderr, os.Stderr // keep stdout clean for scripts
	if err := tee.Run(); err != nil {
		return err
	}
	// Without this the resolver cache keeps serving NXDOMAIN for a while.
	_ = run("sudo", "dscacheutil", "-flushcache")
	_ = run("sudo", "killall", "-HUP", "mDNSResponder")
	return nil
}

func Uninstall(domain string) error {
	if err := run("sudo", "rm", "-f", Path(domain)); err != nil {
		return err
	}
	_ = run("sudo", "dscacheutil", "-flushcache")
	_ = run("sudo", "killall", "-HUP", "mDNSResponder")
	return nil
}

// Resolves checks the end-to-end path rather than the config file: dnsmasq up,
// resolver installed, and the OS actually returning loopback for the name.
func Resolves(host string) bool {
	out, err := exec.Command("dscacheutil", "-q", "host", "-a", "name", host).Output()
	return err == nil && strings.Contains(string(out), "127.0.0.1")
}

func run(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Stdout, cmd.Stderr, cmd.Stdin = os.Stderr, os.Stderr, os.Stdin
	return cmd.Run()
}
