// Package edge generates the per-project artefacts the long-running containers
// read: a caddy site file and a pgweb bookmark.
//
// Both are plain files in DRAGONRUN_HOME, mounted read-only into the
// containers. Registering a project therefore never restarts the stack -- caddy
// gets a reload, pgweb picks bookmarks up on next page load.
package edge

import (
	"crypto/sha1"
	"crypto/x509"
	"encoding/hex"
	"encoding/pem"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"git.dragonsecurity.io/dragonrun/internal/registry"
	"git.dragonsecurity.io/dragonrun/internal/stack"
)

// Lifetimes for the certificates caddy's local CA issues. `tls internal`
// defaults to a 12-hour leaf off a 7-day intermediate, which assumes a server
// that is always up to renew them. A dev edge is stopped overnight and hit
// again in the morning, and by then the certificate has expired.
//
// A leaf is truncated to its issuer's notAfter, so the intermediate has to
// comfortably outlive it. Caddy renews the intermediate with a third of its
// life left -- four months here -- which is still longer than a whole leaf
// lifetime, so a leaf is never issued short. 90 days also stays under the
// 398-day ceiling browsers apply to server certificates.
//
// CertLifetime is written into each generated site file. IntermediateLifetime
// is a global option and lives in the stack's Caddyfile; the constant is here
// so the two are stated together, and a test keeps them equal.
const (
	CertLifetime         = "2160h" // 90 days
	IntermediateLifetime = "8760h" // 365 days
)

func sitesDir() (string, error) {
	h, err := registry.Home()
	if err != nil {
		return "", err
	}
	return filepath.Join(h, "caddy", "sites"), nil
}

func bookmarksDir() (string, error) {
	h, err := registry.Home()
	if err != nil {
		return "", err
	}
	return filepath.Join(h, "pgweb", "bookmarks"), nil
}

// WriteSite renders the reverse proxy entry. The upstream is
// host.docker.internal because the app runs on the HOST under mprocs -- caddy
// is the only part of the request path that lives in docker.
func WriteSite(p registry.Project) error {
	dir, err := sitesDir()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	body := fmt.Sprintf(`# Generated by dragonrun for %q -- do not edit by hand.
%s {
	tls {
		issuer internal {
			lifetime %s
		}
	}

	reverse_proxy host.docker.internal:%d {
		# Fail fast and say so, rather than hanging, when the app is not
		# running yet. This is the single most common state during dev.
		lb_try_duration 1s
	}

	handle_errors {
		respond "dragonrun: nothing listening on host port %d for %s ({err.status_code})" 502
	}
}
`, p.Name, p.Host, CertLifetime, p.Upstream, p.Upstream, p.Name)
	return os.WriteFile(filepath.Join(dir, p.Name+".caddy"), []byte(body), 0o644)
}

// WriteAllSites regenerates every registered project's site file.
//
// A site file is a pure function of the registry entry behind it, so rewriting
// them all is how a change to what dragonrun generates -- a certificate
// lifetime, say -- reaches projects that were registered by an older binary.
// Without this they keep whatever `register` wrote, however long ago.
func WriteAllSites(c *registry.Config) error {
	for _, p := range c.Sorted() {
		if err := WriteSite(p); err != nil {
			return err
		}
	}
	return nil
}

// ServiceHosts are the built-in UIs dragonrun serves under its own domain, so
// you never have to remember a port. They proxy to the CONTAINERS by service
// name -- caddy shares a network with them -- rather than back out through the
// host's published ports.
//
// These are browser URLs, which is why a hostname is fine here while the
// database and SMTP DSNs deliberately stay on localhost: a browser URL failing
// off-network is a mild annoyance, an app failing to boot is not.
var ServiceHosts = map[string]string{
	"mail":  "mailpit:8025",
	"pgweb": "pgweb:8081",
}

// WriteServiceSites renders the built-in hostnames. One file, rewritten
// whenever the stack comes up, named with a leading underscore so it can never
// collide with a project's own site file.
func WriteServiceSites(c *registry.Config) error {
	dir, err := sitesDir()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	names := make([]string, 0, len(ServiceHosts))
	for n := range ServiceHosts {
		names = append(names, n)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("# Generated by dragonrun -- built-in service UIs. Do not edit by hand.\n")
	for _, n := range names {
		fmt.Fprintf(&b, `
%s.%s {
	tls {
		issuer internal {
			lifetime %s
		}
	}
	reverse_proxy %s
}
`, n, c.Domain, CertLifetime, ServiceHosts[n])
	}
	return os.WriteFile(filepath.Join(dir, "_services.caddy"), []byte(b.String()), 0o644)
}

func RemoveSite(name string) error {
	dir, err := sitesDir()
	if err != nil {
		return err
	}
	err = os.Remove(filepath.Join(dir, name+".caddy"))
	if os.IsNotExist(err) {
		return nil
	}
	return err
}

// WriteBookmark points pgweb at the project's control database as the cluster
// superuser, so tenant databases created later are reachable from the UI's
// database switcher without any further registration.
//
// It connects to postgres directly rather than through pgbouncer: browsing is
// a session-oriented workload and transaction pooling would only get in the way.
func WriteBookmark(c *registry.Config, p registry.Project) error {
	dir, err := bookmarksDir()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	body := fmt.Sprintf(`# Generated by dragonrun for %q -- do not edit by hand.
host = "postgres"
port = 5432
user = %q
password = %q
database = %q
sslmode = "disable"
`, p.Name, c.Superuser, c.SuperuserPassword, p.DB)
	return os.WriteFile(filepath.Join(dir, p.Name+".toml"), []byte(body), 0o600)
}

func RemoveBookmark(name string) error {
	dir, err := bookmarksDir()
	if err != nil {
		return err
	}
	err = os.Remove(filepath.Join(dir, name+".toml"))
	if os.IsNotExist(err) {
		return nil
	}
	return err
}

// Reload asks caddy to re-read its config in place. A restart would drop
// in-flight requests and, more annoyingly, re-issue certificates.
func Reload() error {
	if !stack.Running() {
		return nil // nothing to reload; files are picked up at next `up`
	}
	_, err := stack.ComposeOut("exec", "-T", "caddy",
		"caddy", "reload", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile")
	return err
}

// Where caddy keeps the local CA and the certificates it has issued, inside
// its data volume.
const (
	caddyPKI   = "/data/caddy/pki/authorities/local"
	caddyCerts = "/data/caddy/certificates/local"
)

// EnsureCertLifetimes brings a running stack's certificates up to the
// lifetimes above, and reports whether it had to change anything.
//
// Raising them in config is not enough on a stack that has already run. Caddy
// keeps the intermediate it minted under the old settings until it is nearly
// expired, and truncates every leaf to that date; it also keeps each cached
// leaf until that leaf's own renewal window. An install upgraded in place
// would go on serving twelve-hour certificates -- silently, which is the whole
// bug.
//
// Deleting the intermediate makes caddy mint a replacement from the SAME root,
// so nothing has to be re-trusted and no keychain entry goes stale. The cached
// leaves go with it so every site is re-issued now rather than at its next
// renewal.
func EnsureCertLifetimes() (bool, error) {
	if !stack.Running() {
		return false, nil // nothing to inspect; a cold start reads the new config anyway
	}
	want, err := time.ParseDuration(CertLifetime)
	if err != nil {
		return false, err
	}
	// One read over everything caddy has minted. A certificate issued for less
	// than a full lifetime means the old settings are still in force somewhere
	// -- a short intermediate, or a leaf cached before the change.
	out, err := stack.ComposeOut("exec", "-T", "caddy", "sh", "-c",
		"cat "+caddyPKI+"/intermediate.crt "+caddyCerts+"/*/*.crt 2>/dev/null")
	if err != nil || strings.TrimSpace(out) == "" {
		return false, nil // no CA yet; whatever caddy mints next is already long-lived
	}
	if !anyShorterThan([]byte(out), want) {
		return false, nil
	}
	if _, err := stack.ComposeOut("exec", "-T", "caddy", "rm", "-rf",
		caddyPKI+"/intermediate.crt", caddyPKI+"/intermediate.key", caddyCerts); err != nil {
		return false, err
	}
	// A restart, not a reload: the pki app mints the missing intermediate when
	// it provisions, and caddy's in-memory certificate cache has to go with it.
	if _, err := stack.ComposeOut("restart", "caddy"); err != nil {
		return false, err
	}
	return true, nil
}

// anyShorterThan reports whether any certificate in a PEM bundle was issued for
// less than d. The hour of slack absorbs the time between caddy deciding a
// lifetime and signing for it.
func anyShorterThan(bundle []byte, d time.Duration) bool {
	for {
		var block *pem.Block
		block, bundle = pem.Decode(bundle)
		if block == nil {
			return false
		}
		crt, err := x509.ParseCertificate(block.Bytes)
		if err != nil {
			continue // not a certificate; a key alongside one, say
		}
		if crt.NotAfter.Sub(crt.NotBefore) < d-time.Hour {
			return true
		}
	}
}

// SiteFiles lists the project site files present on disk, by project name.
// The built-in `_services.caddy` is dragonrun's own and never a project.
func SiteFiles() ([]string, error) {
	dir, err := sitesDir()
	if err != nil {
		return nil, err
	}
	ents, err := os.ReadDir(dir)
	if err != nil {
		return nil, nil // no sites directory yet is not an error to report
	}
	var out []string
	for _, e := range ents {
		n := e.Name()
		if e.IsDir() || !strings.HasSuffix(n, ".caddy") || strings.HasPrefix(n, "_") {
			continue
		}
		out = append(out, strings.TrimSuffix(n, ".caddy"))
	}
	sort.Strings(out)
	return out, nil
}

// Bookmarks lists the pgweb bookmarks present on disk, by project name.
func Bookmarks() ([]string, error) {
	dir, err := bookmarksDir()
	if err != nil {
		return nil, err
	}
	ents, err := os.ReadDir(dir)
	if err != nil {
		return nil, nil
	}
	var out []string
	for _, e := range ents {
		n := e.Name()
		if e.IsDir() || !strings.HasSuffix(n, ".toml") {
			continue
		}
		out = append(out, strings.TrimSuffix(n, ".toml"))
	}
	sort.Strings(out)
	return out, nil
}

// CertHosts lists the hostnames caddy holds a certificate for.
//
// A certificate outlives the site file that caused it: unregister a project
// and caddy keeps its certificate until the volume is recreated, which is how
// a host nobody serves any more goes on looking real.
func CertHosts() ([]string, error) {
	if !stack.Running() {
		return nil, nil
	}
	out, err := stack.ComposeOut("exec", "-T", "caddy", "sh", "-c",
		"ls "+caddyCerts+" 2>/dev/null")
	if err != nil {
		return nil, nil // no certificates issued yet
	}
	var hosts []string
	for _, l := range strings.Split(strings.TrimSpace(out), "\n") {
		if l = strings.TrimSpace(l); l != "" {
			hosts = append(hosts, l)
		}
	}
	sort.Strings(hosts)
	return hosts, nil
}

// RootCA copies caddy's local CA out of the container so it can be trusted by
// the host. Until this is trusted, every https://*.test hit shows a warning.
func RootCA() (string, error) {
	h, err := registry.Home()
	if err != nil {
		return "", err
	}
	out, err := stack.ComposeOut("exec", "-T", "caddy",
		"cat", "/data/caddy/pki/authorities/local/root.crt")
	if err != nil {
		return "", fmt.Errorf("caddy has not generated its local CA yet -- start the stack and hit a site once: %w", err)
	}
	path := filepath.Join(h, "caddy", "root.crt")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, []byte(out), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// UntrustCA removes dragonrun's caddy root from the system keychain.
//
// It matches on the certificate's SHA-1 fingerprint, not its name: the label
// carries a year ("Caddy Local Authority - 2026 ECC Root") and any other Caddy
// on this machine -- one of the per-project Caddyfiles, say -- produces a root
// with the same name. Deleting by name could untrust someone else's CA.
func UntrustCA(rootCrt string) (bool, error) {
	fp, err := fingerprint(rootCrt)
	if err != nil {
		return false, err
	}
	// Confirm it is actually in the keychain before asking for sudo.
	out, err := exec.Command("security", "find-certificate", "-a", "-Z",
		"-c", "Caddy Local Authority", "/Library/Keychains/System.keychain").Output()
	if err != nil || !strings.Contains(string(out), fp) {
		return false, nil
	}
	cmd := exec.Command("sudo", "security", "delete-certificate",
		"-Z", fp, "/Library/Keychains/System.keychain")
	cmd.Stdout, cmd.Stderr, cmd.Stdin = os.Stderr, os.Stderr, os.Stdin
	if err := cmd.Run(); err != nil {
		return false, err
	}
	return true, nil
}

// Fingerprint returns the SHA-1 of a PEM certificate, formatted the way
// `security find-certificate -Z` prints it.
func Fingerprint(path string) (string, error) { return fingerprint(path) }

// KeychainCAs lists every trusted caddy root, by fingerprint. Used to find
// roots left behind when the caddy volume was recreated.
func KeychainCAs() ([]string, error) {
	out, err := exec.Command("security", "find-certificate", "-a", "-Z",
		"-c", "Caddy Local Authority", "/Library/Keychains/System.keychain").Output()
	if err != nil {
		return nil, nil // none present, or no keychain access
	}
	var fps []string
	for _, line := range strings.Split(string(out), "\n") {
		if _, hash, ok := strings.Cut(line, "SHA-1 hash: "); ok {
			fps = append(fps, strings.TrimSpace(hash))
		}
	}
	return fps, nil
}

// DeleteCA removes one certificate from the system keychain by fingerprint.
func DeleteCA(fp string) error {
	cmd := exec.Command("sudo", "security", "delete-certificate",
		"-Z", fp, "/Library/Keychains/System.keychain")
	cmd.Stdout, cmd.Stderr, cmd.Stdin = os.Stderr, os.Stderr, os.Stdin
	return cmd.Run()
}

// fingerprint returns the SHA-1 of a PEM certificate, formatted the way
// `security find-certificate -Z` prints it (uppercase hex, no separators).
func fingerprint(path string) (string, error) {
	pemBytes, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	block, _ := pem.Decode(pemBytes)
	if block == nil {
		return "", fmt.Errorf("%s is not a PEM certificate", path)
	}
	sum := sha1.Sum(block.Bytes)
	return strings.ToUpper(hex.EncodeToString(sum[:])), nil
}

// TrustCA installs caddy's root into the system keychain. Requires sudo, and
// deliberately shells out visibly so the password prompt is not a surprise.
func TrustCA(path string) error {
	cmd := exec.Command("sudo", "security", "add-trusted-cert",
		"-d", "-r", "trustRoot", "-k", "/Library/Keychains/System.keychain", path)
	cmd.Stdout, cmd.Stderr, cmd.Stdin = os.Stdout, os.Stderr, os.Stdin
	return cmd.Run()
}
