// Package edge generates the per-project artefacts the long-running containers
// read: a caddy site file and a pgweb bookmark.
//
// Both are plain files in DRAGONRUN_HOME, mounted read-only into the
// containers. Registering a project therefore never restarts the stack -- caddy
// gets a reload, pgweb picks bookmarks up on next page load.
package edge

import (
	"crypto/sha1"
	"encoding/hex"
	"encoding/pem"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"git.dragonsecurity.io/dragonrun/internal/registry"
	"git.dragonsecurity.io/dragonrun/internal/stack"
)

func sitesDir() (string, error) {
	h, err := registry.Home()
	if err != nil {
		return "", err
	}
	return filepath.Join(h, "caddy", "sites"), nil
}

func bookmarksDir() (string, error) {
	h, err := registry.Home()
	if err != nil {
		return "", err
	}
	return filepath.Join(h, "pgweb", "bookmarks"), nil
}

// WriteSite renders the reverse proxy entry. The upstream is
// host.docker.internal because the app runs on the HOST under mprocs -- caddy
// is the only part of the request path that lives in docker.
func WriteSite(p registry.Project) error {
	dir, err := sitesDir()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	body := fmt.Sprintf(`# Generated by dragonrun for %q -- do not edit by hand.
%s {
	tls internal

	reverse_proxy host.docker.internal:%d {
		# Fail fast and say so, rather than hanging, when the app is not
		# running yet. This is the single most common state during dev.
		lb_try_duration 1s
	}

	handle_errors {
		respond "dragonrun: nothing listening on host port %d for %s ({err.status_code})" 502
	}
}
`, p.Name, p.Host, p.Upstream, p.Upstream, p.Name)
	return os.WriteFile(filepath.Join(dir, p.Name+".caddy"), []byte(body), 0o644)
}

// ServiceHosts are the built-in UIs dragonrun serves under its own domain, so
// you never have to remember a port. They proxy to the CONTAINERS by service
// name -- caddy shares a network with them -- rather than back out through the
// host's published ports.
//
// These are browser URLs, which is why a hostname is fine here while the
// database and SMTP DSNs deliberately stay on localhost: a browser URL failing
// off-network is a mild annoyance, an app failing to boot is not.
var ServiceHosts = map[string]string{
	"mail":  "mailpit:8025",
	"pgweb": "pgweb:8081",
}

// WriteServiceSites renders the built-in hostnames. One file, rewritten
// whenever the stack comes up, named with a leading underscore so it can never
// collide with a project's own site file.
func WriteServiceSites(c *registry.Config) error {
	dir, err := sitesDir()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	names := make([]string, 0, len(ServiceHosts))
	for n := range ServiceHosts {
		names = append(names, n)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("# Generated by dragonrun -- built-in service UIs. Do not edit by hand.\n")
	for _, n := range names {
		fmt.Fprintf(&b, `
%s.%s {
	tls internal
	reverse_proxy %s
}
`, n, c.Domain, ServiceHosts[n])
	}
	return os.WriteFile(filepath.Join(dir, "_services.caddy"), []byte(b.String()), 0o644)
}

func RemoveSite(name string) error {
	dir, err := sitesDir()
	if err != nil {
		return err
	}
	err = os.Remove(filepath.Join(dir, name+".caddy"))
	if os.IsNotExist(err) {
		return nil
	}
	return err
}

// WriteBookmark points pgweb at the project's control database as the cluster
// superuser, so tenant databases created later are reachable from the UI's
// database switcher without any further registration.
//
// It connects to postgres directly rather than through pgbouncer: browsing is
// a session-oriented workload and transaction pooling would only get in the way.
func WriteBookmark(c *registry.Config, p registry.Project) error {
	dir, err := bookmarksDir()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	body := fmt.Sprintf(`# Generated by dragonrun for %q -- do not edit by hand.
host = "postgres"
port = 5432
user = %q
password = %q
database = %q
sslmode = "disable"
`, p.Name, c.Superuser, c.SuperuserPassword, p.DB)
	return os.WriteFile(filepath.Join(dir, p.Name+".toml"), []byte(body), 0o600)
}

func RemoveBookmark(name string) error {
	dir, err := bookmarksDir()
	if err != nil {
		return err
	}
	err = os.Remove(filepath.Join(dir, name+".toml"))
	if os.IsNotExist(err) {
		return nil
	}
	return err
}

// Reload asks caddy to re-read its config in place. A restart would drop
// in-flight requests and, more annoyingly, re-issue certificates.
func Reload() error {
	if !stack.Running() {
		return nil // nothing to reload; files are picked up at next `up`
	}
	_, err := stack.ComposeOut("exec", "-T", "caddy",
		"caddy", "reload", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile")
	return err
}

// RootCA copies caddy's local CA out of the container so it can be trusted by
// the host. Until this is trusted, every https://*.test hit shows a warning.
func RootCA() (string, error) {
	h, err := registry.Home()
	if err != nil {
		return "", err
	}
	out, err := stack.ComposeOut("exec", "-T", "caddy",
		"cat", "/data/caddy/pki/authorities/local/root.crt")
	if err != nil {
		return "", fmt.Errorf("caddy has not generated its local CA yet -- start the stack and hit a site once: %w", err)
	}
	path := filepath.Join(h, "caddy", "root.crt")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, []byte(out), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// UntrustCA removes dragonrun's caddy root from the system keychain.
//
// It matches on the certificate's SHA-1 fingerprint, not its name: the label
// carries a year ("Caddy Local Authority - 2026 ECC Root") and any other Caddy
// on this machine -- one of the per-project Caddyfiles, say -- produces a root
// with the same name. Deleting by name could untrust someone else's CA.
func UntrustCA(rootCrt string) (bool, error) {
	fp, err := fingerprint(rootCrt)
	if err != nil {
		return false, err
	}
	// Confirm it is actually in the keychain before asking for sudo.
	out, err := exec.Command("security", "find-certificate", "-a", "-Z",
		"-c", "Caddy Local Authority", "/Library/Keychains/System.keychain").Output()
	if err != nil || !strings.Contains(string(out), fp) {
		return false, nil
	}
	cmd := exec.Command("sudo", "security", "delete-certificate",
		"-Z", fp, "/Library/Keychains/System.keychain")
	cmd.Stdout, cmd.Stderr, cmd.Stdin = os.Stderr, os.Stderr, os.Stdin
	if err := cmd.Run(); err != nil {
		return false, err
	}
	return true, nil
}

// fingerprint returns the SHA-1 of a PEM certificate, formatted the way
// `security find-certificate -Z` prints it (uppercase hex, no separators).
func fingerprint(path string) (string, error) {
	pemBytes, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	block, _ := pem.Decode(pemBytes)
	if block == nil {
		return "", fmt.Errorf("%s is not a PEM certificate", path)
	}
	sum := sha1.Sum(block.Bytes)
	return strings.ToUpper(hex.EncodeToString(sum[:])), nil
}

// TrustCA installs caddy's root into the system keychain. Requires sudo, and
// deliberately shells out visibly so the password prompt is not a surprise.
func TrustCA(path string) error {
	cmd := exec.Command("sudo", "security", "add-trusted-cert",
		"-d", "-r", "trustRoot", "-k", "/Library/Keychains/System.keychain", path)
	cmd.Stdout, cmd.Stderr, cmd.Stdin = os.Stdout, os.Stderr, os.Stdin
	return cmd.Run()
}
