// Package stack materialises the embedded compose stack into DRAGONRUN_HOME
// and drives `docker compose` against it.
//
// The assets are embedded rather than read from the repo so the binary works
// anywhere, and re-extracted on every Up so an upgraded dragonrun cannot end
// up driving a stale compose file.
package stack

import (
	"bytes"
	"crypto/sha1"
	"embed"
	"encoding/hex"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"git.dragonsecurity.io/dragonrun/internal/registry"
)

//go:embed all:assets
var assets embed.FS

// Dir is where the stack is extracted. Generated per-project files live
// alongside it under caddy/sites and pgweb/bookmarks.
func Dir() (string, error) {
	h, err := registry.Home()
	if err != nil {
		return "", err
	}
	return filepath.Join(h, "stack"), nil
}

// Extract writes the embedded assets to disk, overwriting what is there. Only
// the files dragonrun owns are touched -- caddy/sites and pgweb/bookmarks live
// outside this tree precisely so they survive.
func Extract() (string, error) {
	dir, err := Dir()
	if err != nil {
		return "", err
	}
	err = fs.WalkDir(assets, "assets", func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel("assets", p)
		if err != nil {
			return err
		}
		target := filepath.Join(dir, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		b, err := assets.ReadFile(p)
		if err != nil {
			return err
		}
		mode := os.FileMode(0o644)
		if strings.HasSuffix(p, ".sh") {
			mode = 0o755
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		return os.WriteFile(target, b, mode)
	})
	if err != nil {
		return "", err
	}

	h, _ := registry.Home()
	for _, sub := range []string{"caddy/sites", "pgweb/bookmarks"} {
		if err := os.MkdirAll(filepath.Join(h, sub), 0o755); err != nil {
			return "", err
		}
	}
	return dir, nil
}

// WriteEnv renders stack/.env, which compose interpolates. It carries the two
// cluster secrets and never the per-project ones.
func WriteEnv(c *registry.Config) error {
	dir, err := Dir()
	if err != nil {
		return err
	}
	h, err := registry.Home()
	if err != nil {
		return err
	}
	body := fmt.Sprintf(""+
		"# Generated by dragonrun -- edits are overwritten on `dragonrun up`.\n"+
		"SUPERUSER=%s\n"+
		"SUPERUSER_PASSWORD=%s\n"+
		"PGBOUNCER_AUTH_PASSWORD=%s\n"+
		"DRAGONRUN_HOME=%s\n"+
		"BIND_EDGE=%s\n"+
		"PORT_POSTGRES=%d\nPORT_BOUNCER=%d\nPORT_SMTP=%d\nPORT_MAILUI=%d\n"+
		"PORT_PGWEB=%d\nPORT_HTTP=%d\nPORT_HTTPS=%d\nPORT_DNS=%d\n",
		c.Superuser, c.SuperuserPassword, c.PgbouncerAuthPassword, h, bindEdge(c),
		c.Ports.Postgres, c.Ports.Bouncer, c.Ports.SMTP, c.Ports.MailUI,
		c.Ports.Pgweb, c.Ports.HTTP, c.Ports.HTTPS, c.Ports.DNS)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, ".env"), []byte(body), 0o600)
}

// bindEdge is the address compose publishes caddy on. An empty Bind is a
// registry written before the setting existed, not a request for 0.0.0.0.
func bindEdge(c *registry.Config) string {
	if c.Bind == "" {
		return registry.DefaultBind
	}
	return c.Bind
}

// ProjectName is the docker compose project this DRAGONRUN_HOME owns.
//
// The compose file carries `name: dragonrun`, which means every instance on the
// machine would share containers AND volumes regardless of DRAGONRUN_HOME. A
// throwaway instance pointed at a scratch home would then quietly adopt the
// real stack's postgres volume, and its `down -v` would destroy real data.
// Deriving the name from the home path makes instances genuinely independent.
func ProjectName() string {
	home, err := registry.Home()
	if err != nil {
		return "dragonrun"
	}
	if h, err := os.UserHomeDir(); err == nil {
		if home == filepath.Join(h, ".dragonrun") {
			return "dragonrun" // the normal case keeps a stable, readable name
		}
	}
	sum := sha1.Sum([]byte(home))
	return "dragonrun-" + hex.EncodeToString(sum[:])[:8]
}

func composeArgs(dir string, args ...string) []string {
	base := []string{
		"compose",
		"-p", ProjectName(),
		"--project-directory", dir,
		"-f", filepath.Join(dir, "docker-compose.yml"),
		"--env-file", filepath.Join(dir, ".env"),
	}
	// The profile must be passed on EVERY compose call, not just `up`:
	// omitting it on `down` would leave an orphaned dnsmasq running and still
	// holding the DNS port.
	if dnsProfile {
		base = append(base, "--profile", "dnsmasq")
	}
	return append(base, args...)
}

// dnsProfile mirrors the registry's DNS mode. Set once by SetDNSMode before
// any compose call; defaults to off so a config-less call cannot start a
// resolver the user did not ask for.
var dnsProfile bool

func SetDNSMode(mode string) { dnsProfile = mode == registry.DNSDnsmasq }

// ComposeArgs returns the full `docker` argv for a compose subcommand.
//
// It exists for callers that cannot go through Compose or ComposeOut --
// provision has to pipe a script into psql's stdin, and to hand a real
// terminal to an interactive one -- so that the project name is still decided
// in exactly one place. Building the argv by hand instead silently drops the
// `-p`, and since the compose file carries `name: dragonrun`, every such call
// lands on the DEFAULT instance's containers however DRAGONRUN_HOME is set.
func ComposeArgs(args ...string) ([]string, error) {
	dir, err := Dir()
	if err != nil {
		return nil, err
	}
	return composeArgs(dir, args...), nil
}

// Compose runs a docker compose subcommand with output attached to the terminal.
func Compose(args ...string) error {
	dir, err := Dir()
	if err != nil {
		return err
	}
	cmd := exec.Command("docker", composeArgs(dir, args...)...)
	cmd.Stdout, cmd.Stderr, cmd.Stdin = os.Stdout, os.Stderr, os.Stdin
	return cmd.Run()
}

// ComposeOut runs a subcommand and captures stdout, for machine-read output.
func ComposeOut(args ...string) (string, error) {
	dir, err := Dir()
	if err != nil {
		return "", err
	}
	var out, errb bytes.Buffer
	cmd := exec.Command("docker", composeArgs(dir, args...)...)
	cmd.Stdout, cmd.Stderr = &out, &errb
	if err := cmd.Run(); err != nil {
		return out.String(), fmt.Errorf("docker compose %s: %w: %s",
			strings.Join(args, " "), err, strings.TrimSpace(errb.String()))
	}
	return out.String(), nil
}

// Running reports whether the postgres container is up, which every
// provisioning command needs before it can do anything useful.
func Running() bool {
	out, err := ComposeOut("ps", "-q", "postgres")
	return err == nil && strings.TrimSpace(out) != ""
}

func RequireDocker() error {
	if _, err := exec.LookPath("docker"); err != nil {
		return fmt.Errorf("docker not found on PATH -- dragonrun needs a docker runtime")
	}
	if err := exec.Command("docker", "info").Run(); err != nil {
		return fmt.Errorf("docker is installed but not responding -- is the daemon running?")
	}
	return nil
}
